# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 05:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SharedModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('related_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared_app.RelatedModel')),
            ],
        ),
        migrations.CreateModel(
            name='ToBeDeletedModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('related_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared_app.RelatedModel')),
            ],
        ),
    ]
