# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 05:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tobedeletedmodel',
            name='related_obj',
        ),
        migrations.DeleteModel(
            name='ToBeDeletedModel',
        ),
    ]
